In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv(r"C:\Users\brahi\Desktop\credit-card-fraud-mlops\data\raw\creditcard.csv")

In [4]:
x=df.drop('Class',axis=1)
y=df['Class']

x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,test_size=0.2,random_state=42)

We need to scale Amount only because other features are already scaled

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train["Amount"]=scaler.fit_transform(x_train[["Amount"]])
x_test["Amount"]=scaler.transform(x_test[["Amount"]])

In [11]:
#    Verify data first (quick check for x_train and x_test  to confirm the scale for Amount feature)
x_train.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
265518,161919.0,1.946747,-0.752526,-1.355130,-0.661630,1.502822,4.024933,-1.479661,1.139880,1.406819,...,-0.134435,0.076197,0.297537,0.307915,0.690980,-0.350316,-0.388907,0.077641,-0.032248,-0.322494
180305,124477.0,2.035149,-0.048880,-3.058693,0.247945,2.943487,3.298697,-0.002192,0.674782,0.045826,...,-0.227279,0.038628,0.228197,0.035542,0.707090,0.512885,-0.471198,0.002520,-0.069002,-0.339764
42664,41191.0,-0.991920,0.603193,0.711976,-0.992425,-0.825838,1.956261,-2.212603,-5.037523,0.000772,...,1.280856,-2.798352,0.109526,-0.436530,-0.932803,0.826684,0.913773,0.038049,0.185340,0.346693
198723,132624.0,2.285718,-1.500239,-0.747565,-1.668119,-1.394143,-0.350339,-1.427984,0.010010,-1.118447,...,-0.490642,-0.139670,0.077013,0.208310,-0.538236,-0.278032,-0.162068,0.018045,-0.063005,-0.327360
82325,59359.0,-0.448747,-1.011440,0.115903,-3.454854,0.715771,-0.147490,0.504347,-0.113817,-0.044782,...,-0.275297,-0.243245,-0.173298,-0.006692,-1.362383,-0.292234,-0.144622,-0.032580,-0.064194,-0.008281

In [10]:
x_test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
263020,160760.0,-0.674466,1.408105,-1.110622,-1.328366,1.388996,-1.308439,1.885879,-0.614233,0.311652,...,0.394322,0.080084,0.810034,-0.224327,0.707899,-0.135837,0.045102,0.533837,0.291319,-0.259954
11378,19847.0,-2.829816,-2.765149,2.537793,-1.074580,2.842559,-2.153536,-1.795519,-0.250020,3.073504,...,-0.515765,-0.295555,0.109305,-0.813272,0.042996,-0.027660,-0.910247,0.110802,-0.511938,-0.304426
147283,88326.0,-3.576495,2.318422,1.306985,3.263665,1.127818,2.865246,1.444125,-0.718922,1.874046,...,2.034786,-1.060151,0.016867,-0.132058,-1.483996,-0.296011,0.062823,0.552411,0.509764,-0.048286
219439,141734.0,2.060386,-0.015382,-1.082544,0.386019,-0.024331,-1.074935,0.207792,-0.338140,0.455091,...,-0.192024,-0.281684,-0.639426,0.331818,-0.067584,-0.283675,0.203529,-0.063621,-0.060077,-0.347741
36939,38741.0,1.209965,1.384303,-1.343531,1.763636,0.662351,-2.113384,0.854039,-0.475963,-0.629658,...,0.009083,-0.164015,-0.328294,-0.154631,0.619449,0.818998,-0.330525,0.046884,0.104527,-0.345707

In [14]:
# chek for Nan value in both x_train and x_test
x_train.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
dtype: int64

In [13]:
x_test.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
dtype: int64

### Handle class imbalance 
Because the  dataset is highly imbalanced (~0.17% fraud)

In [19]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_res, y_train_res = smote.fit_resample(x_train, y_train)

In [18]:
#    Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train_res, y_train_res)

C:\Users\brahi\Desktop\Predict_Employee_Resign_appv2\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
y_pred = model.predict(x_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56864
           1       0.08      0.91      0.15        98

    accuracy                           0.98     56962
   macro avg       0.54      0.95      0.57     56962
weighted avg       1.00      0.98      0.99     56962

In [23]:
print(confusion_matrix(y_test, y_pred))

[[55859  1005]
 [    9    89]]

In [25]:
roc_auc_score(y_test, model.predict_proba(x_test)[:, 1])

np.float64(0.9749760976422084)

We Try better other models :

- Random Forest
- XGBoost

####    RandomForest

In [27]:
from sklearn.ensemble import RandomForestClassifier

RFC =RandomForestClassifier(criterion='gini',max_depth=6,min_samples_leaf=10,random_state=42 )
RFC.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=10, random_state=42)

In [28]:
y_pred_rfc=RFC.predict(x_test)

In [29]:
print(classification_report(y_test, y_pred_rfc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.88      0.76      0.81        98

    accuracy                           1.00     56962
   macro avg       0.94      0.88      0.91     56962
weighted avg       1.00      1.00      1.00     56962

#### XGBoost

In [37]:
import sys
!{sys.executable} -m pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
     -------------------------------------- 101.7/101.7 MB 7.0 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in c:\users\brahi\desktop\predict_employee_resign_appv2\venv\lib\site-packages (from xgboost) (1.17.1)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: C:\Users\brahi\Desktop\Predict_Employee_Resign_appv2\venv\Scripts\python.exe -m pip install --upgrade pip

In [35]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\brahi\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\brahi\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\brahi\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [38]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

model.fit(x_train, y_train)
y_pred_xgb = model.predict(x_test)

In [39]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.93      0.79      0.85        98

    accuracy                           1.00     56962
   macro avg       0.96      0.89      0.93     56962
weighted avg       1.00      1.00      1.00     56962

In [42]:
model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    scale_pos_weight=100
)

model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [43]:
y_proba = model.predict_proba(x_test)[:, 1]

In [44]:
y_pred_th = (y_proba > 0.3).astype(int)

In [46]:
print(classification_report(y_test, y_pred_th))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.85      0.85      0.85        98

    accuracy                           1.00     56962
   macro avg       0.92      0.92      0.92     56962
weighted avg       1.00      1.00      1.00     56962

In [48]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[55859  1005]
 [    9    89]]

In [49]:
print(confusion_matrix(y_test, y_pred_th))

[[56849    15]
 [   15    83]]

In [50]:
import joblib
joblib.dump(model, "xgboost_model.pkl")

['xgboost_model.pkl']

In [51]:
# Save threshold
joblib.dump(0.3, "threshold.pkl")

['threshold.pkl']

#### Conclusion:
The final model selected for deployment was XGBoost. Probability predictions were converted into fraud labels using a tuned decision threshold of 0.30 instead of the default 0.50. This threshold provided a better balance between precision and recall, achieving approximately 0.85 precision and 0.85 recall on the test set.

In [52]:
# save scalar
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [53]:
# check if saved documents can be correctelly loaded and tested
model = joblib.load("xgboost_model.pkl")
threshold = joblib.load("threshold.pkl")
scaler = joblib.load("scaler.pkl")

In [54]:
sample = x_test.head(5)

proba = model.predict_proba(sample)[:, 1]
pred = (proba > threshold).astype(int)

print(proba)
print(pred)

[2.0014117e-05 6.5352060e-06 5.7792127e-05 2.2037939e-05 1.3725160e-04]
[0 0 0 0 0]